id: P1EF0E920
initial_creation_type: input
source_metadata:
  title: Buddha Śākyamuni Prayers & Practices
  language: en
  description: 'Lotsawa House presents the following texts as part of its Prayers
    to Buddha Śākyamuni Series:'
  volume:
    6f940edda05d406da491ce45be8fb53b:
      title: Prayer for the Future of the Dharma
      parent: Aspiration Prayers
    06fd6501996541c294bd7771601bb6cd:
      title: 'The King of Aspiration Prayers: Samantabhadra''s “Aspiration to Good
        Actions” (Zangchö Mönlam)'
      parent: Aspiration Prayers
    9d2f7132cf144ac8801862650c0f32a4:
      title: 'The Sage''s Powerful Words of Truth: A Prayer for the Spread of the
        Omniscient Buddha''s Teachings'
      parent: Aspiration Prayers
    fe2696a45fd34114979ed644cb1227d7:
      title: Verses on the Buddha's Previous Lives
      parent: History
    ca4a4c730d354c2e97ed2b5ef649c1fa:
      title: Short Praise of the Buddha's Deeds
      parent: Buddha's Deeds
    57f4dd0ce9b34a16acf8403a40bb7f3b:
      title: Praise of the Twelve Acts of the Buddha
      parent: Buddha's Deeds
    5d824708842f4c28b83ee0ad55af18e6:
      title: 'Praise of the Buddha: With Skilful Means & Compassion...'
      parent: Buddha's Deeds
    1a177664f48d4e1d836ba4d0a7c6066d:
      title: Verses of Homage to the Buddhas and Bodhisattvas Together with their
        Mantras
      parent: Praise
    1a157090f931468a9e4ad79f1defaf60:
      title: A Brief Practice of Paying Homage and Making Offerings to the Sixteen
        Elders
      parent: Sādhanas
    4e271c9ced2849b3b1d6f015ce8a7533:
      title: 'The Heart of Wish-Fulfilling Jewels: A Brief Practice for Paying Homage
        and Making Offerings to the Buddha together with his retinue of Arhats'
      parent: Sādhanas
    3a43cda98b4b4822b0584c5bb70258a6:
      title: A Practice of Paying Homage and Making Offerings to the Sixteen Elders
      parent: Sādhanas
    0e1b8da2892f4afa92d8d45de465093a:
      title: 'The Treasury of Blessings: A Practice of Buddha Śākyamuni'
      parent: Sādhanas
    b528e82995494720b5db818043c9b015:
      title: 'The Sage who Dispels Mind’s Anguish: Advice from the Guru, the Gentle
        Protector Mañjuśrī on the Means of Accomplishing the Yogas of Śamatha and
        Vipaśyanā'
      parent: Commentaries
created_at: '2022-03-01T03:05:43.223098'
last_modified_at: '2022-03-01T03:05:43.223105'
